base_url = "https://Leticiaaa-oss.github.io"
title = "Leticia Arquitectura"
default_language = "es"
compile_sass = false
build_search_index = false
generate_feeds = false

[markdown]
highlight_code = false

[extra]
author = "Leticia"
description = "Estudiante de Arquitectura. De Lima, viviendo en Madrid."
